### ISSUE TITLE
restore from checkpoint

### ISSUE THREAD

**Issue by Nexus01** [LoveHRTF/YouOnlyLookOnce-TF2.0#11]
If I use Ctrl+C to pause the process of `main.py`, then `python main.py --restore`, will the training process  resume from the latest checkpoint?
The last time I do as above, the terminal printed 
`None`  
`Load checkpoint :  ../checkpoints/ckpt-7`.
Then it began the training from Epoch 0.
So how to restore and continue the last Epoch?
Thanks

**Comment by LoveHRTF** [comment]
`python main.py --restore` forces Tensorfow to the use the last checkpoint listed in `../checkpoints/checkpoint`.

By default, `../checkpoints/checkpoint` will be updated every time a new checkpoint was stored, but may fail to do so when the program was forced to stop, or it could be a new checkpoint was added to the list but the actual checkpoint file fails to be generated. In any of these cases, make sure the actual file matches whatever was listed as the last checkpoint in the file `../checkpoints/checkpoint`

Also, you can find which checkpoint was loaded from the printout information in terminal after `python main.py --restore` was used. The new checkpoints and epochs after restore may always start from 0, but it was actually based on the checkpoint you just loaded, and you can always find the time stamp in `../checkpoints/checkpoint` in regards of when it was actually stored.

**Comment by Nexus01** [comment]
> `python main.py --restore` forces Tensorfow to the use the last checkpoint listed in `../checkpoints/checkpoint`.
> 
> By default, `../checkpoints/checkpoint` will be updated every time a new checkpoint was stored, but may fail to do so when the program was forced to stop, or it could be a new checkpoint was added to the list but the actual checkpoint file fails to be generated. In any of these cases, make sure the actual file matches whatever was listed as the last checkpoint in the file `../checkpoints/checkpoint`
> 
> Also, you can find which checkpoint was loaded from the printout information in terminal after `python main.py --restore` was used. The new checkpoints and epochs after restore may always start from 0, but it was actually based on the checkpoint you just loaded, and you can always find the time stamp in `../checkpoints/checkpoint` in regards of when it was actually stored.

Thank you for your help!
